### ISSUE TITLE
kubeconfig_path is ignored dont is working

### ISSUE THREAD

**Issue by franviera92** [kbst/terraform-provider-kustomization#113]
i working with kubeconfig_raw but the first time worked after time in 2 try again the provider search kubeconfig file :/

**Comment by franviera92** [comment]
`provider "kustomization" {
  #kubeconfig_path = "~/.kube/config"
  kubeconfig_raw = module.kubernetes_engine_auth.kubeconfig_raw
}` 

Error: Get "http://localhost/api?timeout=32s": dial tcp [::1]:80: connect: connection refused

**Comment by pst** [comment]
This probably means the output you refer to is not a valid kubeconfig or does not exist (yet).
