### ISSUE TITLE
Must have files on disk; no way to pass in file content through terraform

### ISSUE THREAD

**Issue by BrandonALXEllisSS** [kbst/terraform-provider-kustomization#114]
In my use case, I'd like to pull a file from a remote data source (like using the http provider), kustomize it, and then launch the kustomized resources.

But I am unable to do so with the provider in it's current state.

This is because the kustomize data sources only rely on folders written to disk and cannot accept a yaml file whose content is generated in terraform.

i.e. To perform my use case, I'd have to 1) use a data source to fetch the file, 2) create a local_file **resource** based on the data source, and 3) create a kustomization_overlay or kustomization_build **data source** based on said resource.

This creates a **data>resource>data** dependency and gives errors when using a for_each or count when reading from the final data source.  
`The "for_each" value depends on resource attributes that cannot be determined until apply, so Terraform cannot predict how many instances will be created`

If there was a way to directly pass in the content of yaml files into the data sources (instead of relying on pre-written files), this error wouldn't exist.

**Comment by angelokurtis** [comment]
Hi @BrandonALXEllisSS 
As an alternative, you can use the `kustomize build` looking to remote targets. 
Just like using kustomize, you can do that using `kustomization_overlay`. 
An important thing is that your URL should follow [hashicorp/go-getter URL format](https://github.com/hashicorp/go-getter#url-format). For example:

```tf
data "kustomization_overlay" "horusec_operator" {
  resources = [
    "https://github.com/ZupIT/horusec-operator/config/default?ref=develop"
  ]
}

resource "kustomization_resource" "horusec_operator" {
  for_each = data.kustomization_overlay.horusec_operator.ids
  manifest = data.kustomization_overlay.horusec_operator.manifests[each.value]
}
```

**Comment by pst** [comment]
The list of strings passed to resources should support anything that is supported in the kustomization.yaml. I don't think it makes sense to have the provider support different things than Kustomize does itself.

**Comment by democracytoday** [comment]
This makes it difficult to use for something like customizing flux installations that use manifests built by terraform, e.g., with the flux terraform provider.

Fundamentally, kustomize is slurping strings. It's a shame to not be able to use this provider with terraform-native resources.

**Comment by pst** [comment]
If the manifests generated by the flux provider do not meet your requirements, I suggest you open an issue with the flux provider to allow configuring the manifests it will generate.

This provider integrates Kustomize into Terraform. It's my opinion, that it should support everything that's supported in a kustomization.yaml. Nothing less, but also nothing more.

**Comment by olfway** [comment]
Another use-case for this – if I want to pass some id from terraform to kustomize as a parameter

For example I use kustomize+helm and I often need to hardcode subnets, security groups, iam roles ids in values.yaml files for helm

**Comment by pst** [comment]
You can define the overlay entirely in Terraform, and then you can use Terraform values and patch the underlying YAML after the helm template. If you want to hear my opinion. Stop using helm from kustomizat. Just helm template, store the result in git, then patch it with kustomize. Much more robust in my experience.

https://registry.terraform.io/providers/kbst/kustomization/latest/docs/data-sources/overlay
