### ISSUE TITLE
kubeconfig_path requires a kubeconfig file to actually exist with the correct structure even if that file will come later

### ISSUE THREAD

**Issue by sotiriougeorge** [kbst/terraform-provider-kustomization#117]
Hello, just to clarify I am pretty new to all this so I may have misunderstood a couple of concepts.

What I have is:
- a terraform module creating an EKS cluster
- a helm chart resource applying some charts 
- kustomize resources that apply several (custom I would guess) resources necessary for the aforementioned charts

My EKS module has a parameter with which it writes a kubeconfig file dynamically during the creation of the cluster on my designated local filesystem as such:
```
module "eks-cluster" {
  source                    = "terraform-aws-modules/eks/aws"
  cluster_name              = var.cluster_name
  cluster_version           = "1.19"
  subnets                   = var.subnets
  vpc_id                    = var.vpc_id
  enable_irsa               = true
  node_groups = {
    first = {
      desired_capacity = 2
      max_capacity     = 4
      min_capacity     = 1
      instance_type    = var.worker_instance_type
    }
  }
  write_kubeconfig   = true
  kubeconfig_output_path = "./kubeconfig"
}
```
I also have this configuration regarding kbst/kustomize:
```
terraform {
  required_providers {
    kustomization = {
      source = "kbst/kustomization"
      version = "0.5.0"
    }
  }
  required_version = ">= 0.12"
}

provider "kustomization" {
  kubeconfig_path = "./kubeconfig"
}
```
When I am executing `terraform plan` I get the following error:
│ Error: provider kustomization: kubeconfig_path: open ./kubeconfig: The system cannot find the file specified.
│
│   with module.eks-cluster.provider["registry.terraform.io/kbst/kustomization"],
│   on ..\modules\k8-eks-cluster\eks\providers.tf line 28, in provider "kustomization":
│   28: provider "kustomization" {

I tried to "trick" it by creating an empty kubeconfig file in the directory but apparently it also requires the structure of the file to be correct so I got the equivalent error which I am not going to paste here as it's out of scope.
Am I doing something wrong? Using this wrong? Is, what I'm trying to do, out of scope for this specific provider? 

P.S. I would like to point out that when the code I am trying to maintain was given to me by another developer it was using
```
version = "0.2.0-beta.3"
```
which did accept the non-existing ./kubeconfig file during planning and applying.

Thank you for your time.

**Comment by pst** [comment]
Try using `kubeconfig_raw` instead. Not knowing that EKS module, but when files are actually written to disk is often depending on what part of the lifecycle Terraform is in. E.g. `local_file` resources aren't written during plan to the best of my knowledge. The way how authentication is handled, changed in v0.5.0. https://github.com/kbst/terraform-provider-kustomization/pull/103
