### ISSUE TITLE
Cannot use resource output in kustomization_overlay

### ISSUE THREAD

**Issue by matthijsvanderloos** [kbst/terraform-provider-kustomization#145]
I am trying to generate a Kubernetes secret similar to what is done in the documentation, i.e. use the `random_password` resource to generate a password and use the output in `secret_generator`:

```hcl
resource "random_password" "password" {
  length = 16
  special = true
  override_special = "_%@"
}

data "kustomization_overlay" "example" {
  secret_generator {
    name = "example-secret1"
    type = "Opaque"
    literals = [
      "password=${random_password.password.result}",
    ]

    options {
      disable_name_suffix_hash = true
    }
  }
}

resource "kustomization_resource" "example" {
  for_each = data.kustomization_overlay.example.ids

  manifest = data.kustomization_overlay.example.manifests[each.value]
}
```

However, this generates the following error when to trying to perform the `terraform plan`:

```
The "for_each" value depends on resource attributes that cannot be determined until apply, 
so Terraform cannot predict how many instances will be created. 
To work around this, use the -target argument to first apply only the resources that the for_each depends on.
```

Is there a recommended way for solving this?

**Comment by Aankhen** [comment]
I just ran into this too. It’s logical if there are resources in the overlay that are going to receive name suffixes on the Kubernetes end, but it would be really useful to mark it as ‘known after apply’ if and only if that is the case.

**Comment by pst** [comment]
It's the `random_password.password` that is known-after-apply and that propagates through the data source, all the way to the `kustomizastion_resource` which uses `for_each`. You can either do the `--target` apply or avoid using `for_each`. Although the latter is difficult if you have more than a handful of resources in the kustomization. Alternatively, you could apply the secret using `kubernetes_secret` after the other resources, especially the namespace have been created from the kustomization.

**Comment by Aankhen** [comment]
Ah, interesting… in my case, it was a [`kubectl_manifest`](https://registry.terraform.io/providers/gavinbunney/kubectl/latest/docs/resources/kubectl_manifest) which isn’t used for anything except sequencing. Guess I’ll use the `kubernetes` provider or something. Thanks for clarifying!
