### ISSUE TITLE
Output contains full manifest of v1/Secret including sensitive data key

### ISSUE THREAD

**Issue by erpel** [kbst/terraform-provider-kustomization#150]
When using `terraform plan` on a kustomziation that includes resources of the v1/Secret kind, the resulting output includes the complete manifest including the actual data portion of the secret.

Providers like https://registry.terraform.io/providers/gavinbunney/kubectl/latest/docs/resources/kubectl_manifest or https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/secret mark the data field as sensitive by default, which keeps them from being printed to the output.

It would be good, if this provider could also check the kind of resources and omit the output for secrets entirely or just declare the data portion to be sensitive.

Not sure if this is possible, currently the only workaround I found was wrapping the manifest in `sensitive(...)`

Example:
```
( # kustomization_resource.apps["secret|cb-billing-default|secret-settings"] will be created
  + resource "kustomization_resource" "apps" {
      + id       = (known after apply)
      + manifest = <<-EOT
            {"apiVersion":"v1","data": [...sensitive data…],"kind":"Secret","metadata":{"name":"secret-settings","namespace":"cb-billing-default"},"type":"Opaque"}
        EOT
    })
```

**Comment by pst** [comment]
If we mark the entire manifest sensitive, there are no diffs anymore. There is a PR here, with more discussion on the topic. https://github.com/kbst/terraform-provider-kustomization/pull/142

**Comment by erpel** [comment]
I wonder how I missed that PR... Thanks for the hint.
The downside of not having diffs is a tradeoff we're currently accepting but I'm sure at some point in the future, this will become more relevant.
