### ISSUE TITLE
Provide support for client-go credential (exec) plugins

### ISSUE THREAD

**Issue by bartcode** [kbst/terraform-provider-kustomization#151]
Unlike the Kubernetes or Helm providers for Terraform, kustomization doesn't support the use of `exec { }`. Would be good if the following will become supported:

```
provider "kustomization" {
  exec {
    api_version = "client.authentication.k8s.io/v1beta1"
    command     = "kubelogin"
    args        = [
      "get-token",
      // ...
    ]
  }
}
```

**Comment by pst** [comment]
You can use exec by giving the provider a kubeconfig that uses exec. The provider is built to expect a kubeconfig and supports anything you can do in a kubeconfig. I don't have plans to play catch-up reimplemeting the kubeconfig schema in Terraform for the various options supported there.
