### ISSUE TITLE
posibility to download git repo with manifests

### ISSUE THREAD

**Issue by holms** [kbst/terraform-provider-kustomization#161]
Currently there's only a way to apply manifests which available locally. But how do I download them with terraform from git repo? I don't think that downloading repo manually  before launching terraform is a good idea. 

For example Helm provider  can access and download helm charts from anywhere. I don't have to keep helm charts locally in order to apply it. Why we can't have the same mechanism with kustomize? I have no idea how to automate such behavior. Currently my whole automation was simply working just by running `terraform apply` until a recent need to use Kuztomize.

Now gitlab-agent decided to use kustomize manifests and no one wrote a helm chart for it, so I'm in a strange situation where I need too perform manual steps in order to download a manifest from a github repo, then patch manifest to add a gitlab token and then I need to deploy it with Kustomize. Yeah I understand this is not a place to discuss my issues about gitlab-agent, but I believe we need some mechanism to fetch repo's from github? As more people will have this need anyway in a near future? 

Maybe we can have discussion about this please? Maybe there's a better approach and downloading git repo is not a provider scope? Would be really grateful for some opinion. 

Thank you :)

**Comment by pst** [comment]
Relying on a repository that may be temporarily unavailable or may even have been deleted is bad practice for reliable infrastructure automation in my personal opinion.

That being said however, Kustomize does support remote kustomizations, they can be specified with some special format string under manifests. I suggest you refer to the Kustomize documentation.

As I've stated many times in issues here, I don't use the remote feature and therefor will not invest my time to support it. If it works, fine, if it doesn't, somebody else will have to step up to support it.

**Comment by holms** [comment]
> Relying on a repository that may be temporarily unavailable or may even have been deleted is bad practice for reliable infrastructure automation in my personal opinion.
> 
> 
> 
> That being said however, Kustomize does support remote kustomizations, they can be specified with some special format string under manifests. I suggest you refer to the Kustomize documentation.
> 
> 
> 
> As I've stated many times in issues here, I don't use the remote feature and therefor will not invest my time to support it. If it works, fine, if it doesn't, somebody else will have to step up to support it.

- It's actually the same argument that a  helm chart repo would disappear or any Linux package repo would disappear. Now I need to install multiple apps, and I need to store their manifests in same repo as automation code? Or I need to have git submodules? Kustomize should be a package manager. I'm not sure what the point of having manifests if they can't be portable and there is no mechanism to transfer them from anywhere. Kustomize should be alternative of helm..

**Comment by pst** [comment]
Well, I personally disagree strongly with you. And I never use helm for anything important anyway.

But I gave you a hint how to achieve what you're trying to do. And it doesn't need to involve me.
