### ISSUE TITLE
feature request: provide input files as input parameters

### ISSUE THREAD

**Issue by balonik** [kbst/terraform-provider-kustomization#163]
Hello,

I would like to request a feature, where it will be possible to provide manifests and kustomization file as input parameters. This would allow to build kustomization for use-cases where the manifests are coming from other providers' data sources.

For `kustomization_build`:
2 input parameters, one for original manifests and one for kustomization definition.
New parameters could be mutually exclusive with the existing `path` input parameter.

For `kustomization_overlay`:
1 input parameter for original manifests.
New parameter could be mutually exclusive with the existing `resources` input parameter.

I am currently using `local_file` as a workaround, but it is causing noise in TF plans.

**Comment by pst** [comment]
This is not in scope for the provider. More information on the topic can be found here: https://github.com/kbst/terraform-provider-kustomization/issues/114
