### ISSUE TITLE
Previous schema data sources in state fail after provider upgrade to v0.8.0

### ISSUE THREAD

**Issue by pstwp** [kbst/terraform-provider-kustomization#169]
```
╷
│ Error: .patches[0].target: missing expected [
│ 
│ 
╵
```

Since this only affects the `kustomization_overlay` data source, a possible workaround is to delete just the data source from state manually.

```
terraform state rm data.kustomization_overlay.current
```

Alternatively stay on the previous version of the provider until this issue has been fixed.

**Comment by pst** [comment]
My first theory was, that I should have written a state migration, and that I forgot this and it's therefor a bug in the provider I have to fix.

But it seems [one can not write state migrations for data sources according to this post](https://discuss.hashicorp.com/t/do-data-sources-support-state-migrations/37305).

> Data resources do not require state migrations. They are read-only resources, so the action of reading them updates the state to the latest version. For this reason, Terraform does not call the UpgradeResourceState method for data sources.

**Comment by pst** [comment]
Terraform 1.1.9 includes a fix for the root cause: https://github.com/hashicorp/terraform/blob/v1.1.9/CHANGELOG.md#119-april-20-2022
