### ISSUE TITLE
Lookup for kubernetes value not working

### ISSUE THREAD

**Issue by AndrewZeitler** [kbst/terraform-provider-kustomization#180]
Hey,

I am trying to use kustomization_overlay to patch some helm charts I am pulling from a repo. The helm chart contains a lookup for one of the values in our kubernetes cluster. However, this lookup never seems to work. The lookup line from the chart is as follows:

```
data:
  {{- $key := lookup "v1" "Secret" .Release.Namespace "gradle-build-cache-builtin-secret" | dig "data" "build.cache.builtin.secret" "" | b64dec }}
  build.cache.builtin.secret: '{{ $key | default (randAlphaNum 16) | b64enc }}'
```

The value always defaults to the random number. Does anyone know why this might be? This chart works as expected when we are not using this provider.

We have tried changing the .Release.Namespace in the chart to match the namespace in our cluster (to make sure we weren't setting the namespace improperly) but it still fails.
We also made sure that this helm chart was being run by setting it to some test value and we saw that appear in our plan.

Thanks!

**Comment by pst** [comment]
I don't use helm, the support for helm was contributed and I accepted it. But I won't be able to assist with issues around it.

**Comment by olfway** [comment]
AFAIK kustomize uses helm template and it doesn't have access to your k8s cluster.

**Comment by pst** [comment]
Thanks for the insight @olfway. I assume with that, we can close this issue. I don't think any sort of dynamic lookups helm might be doing would work with the integration kustomize has.
