### ISSUE TITLE
kustomize_options

### ISSUE THREAD

**Issue by andruwa13** [kbst/terraform-provider-kustomization#184]
version 0.8.2

Error: Unsupported argument 
 An argument named "kustomize_options" is not expected here. Did you mean to define a block of type "kustomize_options"?

```
data "kustomization_overlay" "wordpress" {

  resources = [
    "deploy",
  ]

  namespace = "wordpress"
  name_prefix = "ex-"

  kustomize_options = {
    load_restrictor = "none"
    enable_helm = true
    helm_path = "/usr/local/bin/helm"
  }
}
```

P.S. On the version of 0.7.2 everything works

**Comment by pst** [comment]
The schema had to be changed to upgrade to SDK v2 in 0.8.0, it's a block now: 

```hcl
kustomize_options {
    load_restrictor = "none"
    enable_helm = true
    helm_path = "/usr/local/bin/helm"
  }
  ```

**Comment by andruwa13** [comment]
Please correct in the documentation

**Comment by pst** [comment]
Feel free to send a PR.

**Comment by mwmahlberg** [comment]
This is seemingly not reflected in https://registry.terraform.io/providers/kbst/kustomization/latest/docs/data-sources/build
<img width="1440" alt="Bildschirm­foto 2022-11-12 um 11 43 28" src="https://user-images.githubusercontent.com/138420/201470520-3ac44364-17ac-4d07-8219-12d4a02570b4.png">

**Comment by andreapigatto** [comment]
> The schema had to be changed to upgrade to SDK v2 in 0.8.0, it's a block now:
> 
> ```hcl
> kustomize_options {
>     load_restrictor = "none"
>     enable_helm = true
>     helm_path = "/usr/local/bin/helm"
>   }
> ```

what about running Terraform CLI via Terraform Cloud? I'm not able to set the helm_path cause helm binary seems not available. Any ideas? Thanks
