### ISSUE TITLE
Upgrading from 0.7.2 to 0.8.2 causes error due to state mismatch

### ISSUE THREAD

**Issue by kadamanas93** [kbst/terraform-provider-kustomization#185]
I have been using version 0.7.2 of the kustomization provider and want to upgrade to 0.8.2 but am unable to as the provider can't read the existing state file. `terraform plan` results in issues with the type for `kustomize_options` and `target` which were updated from a map to a list of maps.

This is the error I get:
```
Error: .kustomize_options: missing expected [
```

Manually pulling down the state file and converting `kustomize_options` to a list then pushing the new statefile resolves the issue.

**Comment by pst** [comment]
Update Terraform https://github.com/kbst/terraform-provider-kustomization/issues/169
