### ISSUE TITLE
Allow `ignore_changes` with specific manifest fields

### ISSUE THREAD

**Issue by shivjm** [kbst/terraform-provider-kustomization#200]
I create a cluster with Terraform and use Argo CD to bootstrap it. Certain Secrets need to be created by Terraform, so I create their namespaces on the Terraform side as well. Later, the Argo CD stack augments those namespaces with annotations and labels. When I run Terraform again, it wants to remove the extra metadata.

It would be extremely helpful to be able to specify `ignore_changes` so those fields are ignored (ignoring `metadata` as a whole would also be fine). `ignore_changes = [metadata.annotations]` says there is no `metadata` field on the resource. `ignore_changes = ["_/Namespace/_/observability"]` and `ignore_changes = [_/Namespace/_/observability]` both fail because the slashes aren’t valid.

I also tried targeted planning with copious escaping:[^1]

```powershell
terraform plan "-target=module.argocd.kustomization_resource.argocd1[`"`"`"_/Secret/observability/promscale-connection`"`"`"]"
```

This pulls in dependencies as well, so the namespaces are also altered by the plan, defeating the purpose.

[^1]: PowerShell. (cmd was almost as bad.)

**Comment by pst** [comment]
The resource's manifest is a string from the view of Terraform. If you want to ignore changes, you can only ignore them for the entire manifest attribute.

As for escaping, I don't know anything about powershell. But if you take a look at the docs, the import section has an example of how to escape using single quotes, that works in bash.

**Comment by shivjm** [comment]
> The resource's manifest is a string from the view of Terraform. If you want to ignore changes, you can only ignore them for the entire manifest attribute.

Ah, that’s a shame. I’ll have to find another way to do it.

> As for escaping, I don't know anything about powershell. But if you take a look at the docs, the import section has an example of how to escape using single quotes, that works in bash.

Sorry, I realize now that that was a misleading comment. The snippet works, and PowerShell is responsible for the hilariously absurd quoting.
