### ISSUE TITLE
Simplest example allowing a kustomization.yaml file to be applied

### ISSUE THREAD

**Issue by Dr-Irv** [kbst/terraform-provider-kustomization#202]
In our project, we have a `kustomization.yaml` file all ready to go.  In the command line, we can do `kubectl apply -k directory` where `directory` is the location of the `kustomization.yaml` file, and everything works.

Now we are being asked to move to Terraform, and another team has set up a CI pipeline using Terraform and helm to create the application.  Everything works fine, but we need this last step as part of the pipeline.  We just need to insert the step of the equivalent of `kubectl apply -k directory` into the CI. 

I think that this project has the provider to do the job.  It seems that should be a straightforward way to use `kbst/kustomization` to do this task, but I can't find an example that illustrates how to do this.  My knowledge of Terraform is extremely limited!

**Comment by pst** [comment]
The most convenient way is using the module as described here: https://registry.terraform.io/providers/kbst/kustomization/latest/docs/resources/resource#example-usage

Where the example provides the individual files in the list of resources, you can, just like in a kustomization.yaml, also point at another kustomization by specifying a path to a directory.

You also have to require and configure the provider. The whole thing will look something like this:

```hcl
terraform {
  required_providers {
    kustomization = {
      source = "kbst/kustomization"
    }
  }
}

provider "kustomization" {
  kubeconfig_path = "~/.kube/config"
}

module "example" {
  source  = "kbst.xyz/catalog/custom-manifests/kustomization"
  version = "0.3.0"

  configuration_base_key = "default"  # must match workspace name
  configuration = {
    default = {
      resources = [
        "${path.root}/path/to/kustomization/directory"
      ]
    }
  }
}
```

At the level where `resources` is set, you can also set all other attributes that you can set in a kustomization.yaml, like `namespace` or `config_map_generator`. Documented here: https://www.kubestack.com/framework/documentation/cluster-service-modules#configuration
