### ISSUE TITLE
Allow `resources` in data source `kustomization_overlay` from another terraform resource

### ISSUE THREAD

**Issue by kholisrag** [kbst/terraform-provider-kustomization#209]
would be good to allow `resources` in data source `kustomization_overlay` from another terraform resource block. maybe using `resources_raw` ?

use case : 
- we still didn't have the kustomization directory, and we would like to generate it on the fly,

for example : 
- we want to install flux using terraform flux provider. we know that `data.flux_install.main.content` have yaml that required to be installed, but we want to patch it before install, then we use `kustomization_overlay` to generate the patch, with `resources` inputed from `data.flux_install.main.content`

**Comment by pst** [comment]
My opinion on this topic hasn't changed, I don't think it makes sense for this provider to support more than Kustomize does itself. https://github.com/kbst/terraform-provider-kustomization/issues/114
