### ISSUE TITLE
kubeconfig_path is ignored when using helm_charts

### ISSUE THREAD

**Issue by doczico** [kbst/terraform-provider-kustomization#211]
When using helm_charts block kubeconfig_path is ignored and deployement try to use kubectl current-context instead of the provided configuration

**Comment by pst** [comment]
I already spent time on Slack with you and told you I see no indication that what you are seeing is an issue with the provider. If you want this issue to make sense, it needs more details and a code example that reproduces the issue. Without that there is no point having the issue. I can reopen if you or somebody else provides more detail. At the very least, I need example code that reproduces the issue.
