### ISSUE TITLE
Connect to the cluster using hashicorp/kubernetes parameters

### ISSUE THREAD

**Issue by malacration** [kbst/terraform-provider-kustomization#239]
It would be interesting to connect to the cluster passing parameters like the hashicorp module!

Currently I am sending host, token and cluster_ca_certificate
I will need to take another approach to have two ways of connecting

**Comment by pst** [comment]
By providing a kubeconfig to the provider, you can achieve any sort of configuration you want. I have no plans to support individual kubeconfig attributes on the provider block.
