### ISSUE TITLE
Upgrade to kustomize 5.2.1 to support OCI helm repos

### ISSUE THREAD

**Issue by olfway** [kbst/terraform-provider-kustomization#242]
It was added to kustomize by this pr:
https://github.com/kubernetes-sigs/kustomize/pull/5167

**Comment by pst** [comment]
PR welcome, I don't use helm myself, so it's not a priority to work on this for me.

**Comment by olfway** [comment]
I've made pr, tests passed: https://github.com/olfway/terraform-provider-kustomization/actions/runs/6836327152

Also tested helm part locally

Please have a look
