### ISSUE TITLE
Add support for exec plugin auth

### ISSUE THREAD

**Issue by 0xcd0e** [kbst/terraform-provider-kustomization#246]
We are trying to use this provider on a hosted agent in Azure DevOps, deploying to our AKS with Azure RBAC, and supplying a kubeconfig file in this scenario is not possible.

**Comment by pst** [comment]
You can set the kubeconfig as a terraform local, then use `yamlencode` and pass the result into `kubeconfig_raw`. See: https://registry.terraform.io/providers/kbst/kustomization/latest/docs#example-usage

I have no plans to add any other auth related attributes to the provider.
