### ISSUE TITLE
Issue loading the kustomization provider

### ISSUE THREAD

**Issue by vakkur** [kbst/terraform-provider-kustomization#52]
Error: Failed to validate installed provider

Validating provider local/setup/kustomization v0.2.0-beta.0 failed: provider
binary not found: could not find executable file starting with
terraform-provider-kustomization

![image](https://user-images.githubusercontent.com/54898671/92533291-c1de2a00-f1f7-11ea-8c8b-7f150026b36d.png)

terraform {
  required_version = "> 0.13.0"

  backend "remote" {
    organization = "xxx-dev"

    workspaces {
      name = "xxx-dev"
    }
  }
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "3.4.0"
    }
    kubernetes = {
      source = "hashicorp/kubernetes"
      version = "1.12.0"
    }
    helm = {
      source = "hashicorp/helm"
      version = "1.2.4"
    }
    null = {
      source = "hashicorp/null"
      version = "2.1.2"
    }
    kubernetes-alpha= {
    source= "hashicorp/kubernetes-alpha"
    version = "~> 0.2.0"
  }

    kustomization = {
      source  = "local/setup/kustomization"
      version = "0.2.0-beta.0"
    }
}
}

-------

go version go1.15 linux/amd64

**Comment by pst** [comment]
I haven't tried 0.13 myself yet, but have you see this: https://www.terraform.io/upgrade-guides/0-13.html#new-filesystem-layout-for-local-copies-of-providers

**Comment by pst** [comment]
The provider is available for installation from the official registry now: https://registry.terraform.io/providers/kbst/kustomization/latest

I hope this resolves your issue.
