### ISSUE TITLE
TF registry: provider binary not found: could not find executable file starting with terraform-provider-kustomize

### ISSUE THREAD

**Issue by pst** [kbst/terraform-provider-kustomization#57]
When installing from the TF registry using TF >= 0.13 the following error happens.

```
$ terraform init

Initializing the backend...

Initializing provider plugins...
- Finding kbst/kustomize versions matching "0.2.0-beta.2"...
- Installing kbst/kustomize v0.2.0-beta.2...
- Installed kbst/kustomize v0.2.0-beta.2 (self-signed, key ID A72E13094BE75DDF)

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/plugins/signing.html

Error: Failed to validate installed provider

Validating provider kbst/kustomize v0.2.0-beta.2 failed: provider binary not
found: could not find executable file starting with
terraform-provider-kustomize
```

Before 0.13 the binary was required to be named `terraform-provider-kustomization` because the provider was called `kustomization` and the resources `kustomization` and `kustomization_resource`. Naming the resources this way and then naming the provider accordingly was a mistake I made early on when I didn't know better.

This mistake caused issues (#55 #56), when getting the provider into the registry. And now trying to install from the registry, this new error surfaces.

I believe the fix is to rename the binary from `terraform-provider-kustomization` to `terraform-provider-kustomize`. Publishing the provider in the registry already required the release artifacts (zip files) to follow this naming scheme.

This brings three issues:

 1. Using the provider would probably require a local name that is different from the registry name, [which seems possible](https://www.terraform.io/docs/configuration/provider-requirements.html#handling-local-name-conflicts)

    ```hcl
    terraform {
      required_providers {
        kustomization = {
          source  = "kbst/kustomize"
          version = "0.2.0-beta.2"
        }
      }
    }
    ```

 1. I don't know how to test this theory without making a new release
 1. It is not clear what this means for TF < 0.13

However, the only alternative I see to working around this naming mistake is to rename the provider, resource and data source and align it correctly to have a `kustomize_` prefix as intended by Hashicorp. This would also allow fixing the incorrect navigation links in the docs and the incorrect `terraform` block example in the install instructions.

![Screenshot_2020-10-05 Docs overview kbst kustomize Terraform Registry](https://user-images.githubusercontent.com/253456/95082855-fb815280-071b-11eb-9783-61233bffa6f8.png)

This would probably be cleaner long term, but has the big downside that it would be a backwards incompatible change and would require a yet to be determined `state mv` or `state replace-provider` workflow.

Given the painful alternative, trying to make the unconventional naming work even if it requires another release seems worth a try.

**Comment by pst** [comment]
Another possibility would be to embrace `kustomization` as the name, which would require renaming the repository and republishing it under the changed name in the registry. This would still leave the issue with the data source navigation link, since the data source is named `kustomization` not `kustomization_something`.

**Comment by pst** [comment]
It seems changing the binary name in the release artifact should work. Below I tried this by manually renaming the binary Terraform downloaded and re-running init.

```
$ cd registry.terraform.io/kbst/kustomize/0.2.0-beta.2/linux_amd64/
$ ls
LICENSE  README.md  terraform-provider-kustomization_v0.2.0-beta.2
$ mv terraform-provider-kustomization_v0.2.0-beta.2 terraform-provider-kustomize_v0.2.0-beta.2
```

```
$ terraform init

Initializing the backend...

Initializing provider plugins...
- Using previously-installed kbst/kustomize v0.2.0-beta.2

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```

**Comment by pst** [comment]
```
$ terraform plan

Error: Invalid resource type

  on main.tf line 18, in resource "kustomization_resource" "test":
  18:   for_each = data.kustomization.test.ids

A data resource type "kustomization" is not supported by provider
"registry.terraform.io/hashicorp/kustomize".


Error: Invalid resource type

  on main.tf line 20, in resource "kustomization_resource" "test":
  20:   manifest = data.kustomization.test.manifests[each.value]

A data resource type "kustomization" is not supported by provider
"registry.terraform.io/hashicorp/kustomize".
```

**Comment by pst** [comment]
The above error is confusing. According to the `terraform providers schema` command, the provider has the resource and data source. But the error states `is not supported by provider "registry.terraform.io/hashicorp/kustomize"`. Which has the wrong namespace `hashicorp`, not `kbst`.

```
$ terraform providers schema -json | jq
{
  "format_version": "0.1",
  "provider_schemas": {
    "registry.terraform.io/kbst/kustomize": {
      "provider": {
        "version": 0,
        "block": {
          "attributes": {
            "context": {
              "type": "string",
              "description": "Context to use in kubeconfig with multiple contexts, if not specified the default context is to be used.",
              "description_kind": "plain",
              "optional": true
            },
            "kubeconfig_path": {
              "type": "string",
              "description": "Path to a kubeconfig file. Defaults to '~/.kube/config'.",
              "description_kind": "plain",
              "optional": true
            },
            "kubeconfig_raw": {
              "type": "string",
              "description": "Raw kubeconfig file. If kubeconfig_raw is set,  kubeconfig_path is ignored.",
              "description_kind": "plain",
              "optional": true
            }
          },
          "description_kind": "plain"
        }
      },
      "resource_schemas": {
        "kustomization_resource": {
          "version": 0,
          "block": {
            "attributes": {
              "id": {
                "type": "string",
                "description_kind": "plain",
                "optional": true,
                "computed": true
              },
              "manifest": {
                "type": "string",
                "description_kind": "plain",
                "required": true
              }
            },
            "description_kind": "plain"
          }
        }
      },
      "data_source_schemas": {
        "kustomization": {
          "version": 0,
          "block": {
            "attributes": {
              "id": {
                "type": "string",
                "description_kind": "plain",
                "optional": true,
                "computed": true
              },
              "ids": {
                "type": [
                  "set",
                  "string"
                ],
                "description_kind": "plain",
                "computed": true
              },
              "manifests": {
                "type": [
                  "map",
                  "string"
                ],
                "description_kind": "plain",
                "computed": true
              },
              "path": {
                "type": "string",
                "description_kind": "plain",
                "required": true
              }
            },
            "description_kind": "plain"
          }
        }
      }
    }
  }
}
```

**Comment by pst** [comment]
This behavior seems to be intended when not using the preferred local name. https://www.terraform.io/docs/configuration/provider-requirements.html#local-names

Keeping the current naming would require always specifying the provider attribute. This leads me to the conclusion, that maybe renaming the repository and republishing as `kbst/kustomization` not `kbst/kustomize` on the Terraform registry is the better approach.

**Comment by caueasantos** [comment]
Just to help in further analysis, after applying the changes proposed here I was able to install the provider as well.

**Comment by pst** [comment]
I think I'm gonna do two things to resolve this:

1. I'm going to publish one last release for `kbst/kustomize`, that removes the need to manually rename the artifact and document that this requires specifying the provider attribute. I'll also leave a note in the docs, that this provider will be republished as `kbst/kustomization` to provide the usual user experience.

1. I'm going to rename the repository here, to be able to republish on the registry as `kbst/kustomization` to resolve this.

This seems the best approach, because it does not require changes to the Terraform state.

**Comment by pst** [comment]
I'll also stop using the `-beta.x` suffix for releases because that prevents users from using [version constraints](https://www.terraform.io/docs/configuration/version-constraints.html#version-constraint-behavior).

**Comment by pst** [comment]
The `kbst/kustomize` release has been published and works: https://registry.terraform.io/providers/kbst/kustomize/0.2.0-beta.3

Next I'll work on renaming the repo and republishing as `kbst/kustomization`

**Comment by pst** [comment]
Republished as `kbst/kustomization`: https://registry.terraform.io/providers/kbst/kustomization/0.2.1

**Comment by gnom7** [comment]
Tried to `init` `terraform v0.14.10` with `kbst/kustomization v0.5.0` and got similar issue:
```
Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider
hashicorp/kustomization: provider registry registry.terraform.io does not have
a provider named registry.terraform.io/hashicorp/kustomization
```
Although if I remove all `kustomiztion_*` resources terraform installs provider itself without issues, but still complaining after uncommenting resources back.

**Comment by pst** [comment]
You need to correctly require the provider in the module you init.

```
terraform {
  required_providers {
    kustomization = {
      source  = "kbst/kustomization"
      version = ">= 0.5.0"
    }
  }
}

```
