### ISSUE TITLE
Kustomize Plugins Support

### ISSUE THREAD

**Issue by cguertin14** [kbst/terraform-provider-kustomization#64]
This project seems quite useful. Before integrating in my workflow, I was wondering if the project supports Kustomize plugins (like in the `kustomize build --enable_alpha_plugins example_path/` command?

My use-case is that I would like to automate a Kustomize deployment using Terraform with this library, and to use a Kustomize plugin with my configuration.

Thanks!

**Comment by pst** [comment]
I don't think so. The latest release fixed the built-in plugins. But there is no support for external ones.

**Comment by cguertin14** [comment]
> I don't think so. The latest release fixed the built-in plugins. But there is no support for external ones.

Ok, thank you for the follow-up. I would be interested in contributing to the project and probably integrating such a feature. 
Would it be possible to do so?

**Comment by pst** [comment]
Upstream makes it very clear it's alpha, so as long as that's clear here as well it's fine with me.

You'd probably have to add an attribute to the `kustomization_build` data source and depending on that attribute change the default options returned by `krusty.MakeDefaultOptions()` to allow external plugins.

**Comment by pst** [comment]
I'm closing this because there has not been activity in quite a while.
