### ISSUE TITLE
Clarification: Embedded kubectl Kustomize or kubernetes-sigs?

### ISSUE THREAD

**Issue by dansiviter** [kbst/terraform-provider-kustomization#69]
I can't find any mention if if this is using the [embedded Kustomize](https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/) or the separate [kubernetes-sigs/kustomize](https://github.com/kubernetes-sigs/kustomize). The embedded one is very old (v2.x) and virtually unusable if using CRDs and there is a lot of call to upgrade it (kubernetes/kubectl#818 & kubernetes-sigs/kustomize#1500). Therefore it would be great if this could clarify this and if using the separate kubernetes-sigs/kustomize what version it is leveraging to remove ambiguity.

**Comment by pst** [comment]
You can see the kustomize api version it uses in the [go.mod file](https://github.com/kbst/terraform-provider-kustomization/blob/master/go.mod#L13). If I'm not mistaken, this api version corresponds to v3.8.7 of the standalone kustomize binary.

**Comment by dansiviter** [comment]
@pst So this is using kubernetes-sigs/kustomize directly? If that's the case then that's great. However, without specific domain knowledge this is difficult to ascertain for the layman.

**Comment by pst** [comment]
The provider uses the same kustomize api go module that the standalone kustomize binary uses. It does not use the kustomize binary itself. The provider's kustomize version is fairly recent and has nothing to do with the ancient kustomize that's embedded into kubectl.

**Comment by dansiviter** [comment]
@pst Thanks for the clarification.
