### ISSUE TITLE
Get "http://localhost/api?timeout=32s": dial tcp 127.0.0.1:80: connect: connection refused

### ISSUE THREAD

**Issue by xaoo** [kbst/terraform-provider-kustomization#71]
Hi, 

I am trying to get the this module working, but it seems that no matter what I do, it cannot se the KUBECONFIG either in env vars or default location.

I create the kubeconfig env var with 
https://registry.terraform.io/modules/terraform-google-modules/gcloud/google/latest/submodules/kubectl-wrapper

```module.kubectl-local-yaml.module.gcloud_kubectl.null_resource.run_command[0] (local-exec): + KUBECONFIG=/tmp/kubectl_wrapper_12264_14857/config```

My provider is empty to get default settings:

```
provider "kustomize" {}
```

Main config:

```
data "kustomization" "current" {
  provider = kustomize
  # using the workspace name to select the correct overlay
  path = "manifests/overlays/staging"
}

resource "kustomization_resource" "current" {
  provider = kustomize
  # use the new for_each to handle each resource individually
  for_each = data.kustomization.current.ids
  manifest = data.kustomization.current.manifests[each.value]
}
```

I have tried to create the config file with gcloud within a local-exec, also with a template file.
Nothing get this module to read the file :(, also redirecting the provider to the correct path.

I have also tested the same configuration locally, with config file in default location, works perfectly :(

Any Ideas?

**Comment by pst** [comment]
Only child processes would inherit the env var being set. Not sure if that's the case for Terraform and its providers. Also, the provider may be initialized before the env var is set. I usually use an output from a module or resource as the input for either the path or the raw kubeconfig to this module. That works and I'd go that way, over the dynamic env var approach you are trying here.

https://github.com/kbst/terraform-kubestack/blob/master/common/cluster_services/main.tf

**Comment by xaoo** [comment]
Weird, same results.

Do you have a sample with config file being generated.
Thank you

**Comment by pst** [comment]
Have you read the code I linked?

**Comment by saifmahamood** [comment]
> Only child processes would inherit the env var being set. Not sure if that's the case for Terraform and its providers. Also, the provider may be initialized before the env var is set. I usually use an output from a module or resource as the input for either the path or the raw kubeconfig to this module. That works and I'd go that way, over the dynamic env var approach you are trying here.
> 
> https://github.com/kbst/terraform-kubestack/blob/master/common/cluster_services/main.tf

This file doesn't exist anymore. Has it been moved to a different location? I am getting the same errors mentioned above and wanted to take a look
