### ISSUE TITLE
Is it possible to use a remote path?

### ISSUE THREAD

**Issue by HsnVahedi** [kbst/terraform-provider-kustomization#74]
What's the equivalent of this command:

`kubectl apply -k "github.com/kubernetes-sigs/aws-efs-csi-driver/deploy/kubernetes/overlays/stable/?ref=release-1.0"`

I want to use EFS for my EKS cluster and I'm following this [eks workshop](https://www.eksworkshop.com/beginner/190_efs/).

Is it something like below:

```
terraform {
  required_providers {
    kustomization = {
      source  = "kbst/kustomize"
      version = "v0.2.0-beta.3"
    }
  }
  required_version = ">= 0.12"
}

provider "kustomization" {}

data "kustomization" "test" {
  provider = kustomization

  path = "github.com/kubernetes-sigs/aws-efs-csi-driver/deploy/kubernetes/overlays/stable/?ref=release-1.0"
}


resource "kustomization_resource" "test" {
  provider = kustomization

  for_each = data.kustomization.test.ids

  manifest = data.kustomization.test.manifests[each.value]
}
```

Is it correct? Thanks in advance! I really appreciate it.

**Comment by pst** [comment]
I suggest you use the renamed provider from the official registry. https://registry.terraform.io/providers/kbst/kustomization/latest

Other than that, I don't know how to help you if you don't post an error. Have you even tried it?

**Comment by HsnVahedi** [comment]
Yes, I tried it. @pst It was really slow compared to `kubectl -k` so I thought it wasn't working. But after waiting for a long time it worked.

Thanks for you response.

By the way, There is a little bug in the documentation:

The line: `version = "v0.2.0-beta.3"` should be `version = "0.2.0-beta.3"`
```
terraform {
  required_providers {
    kustomization = {
      # version = "v0.2.0-beta.3"
      version = "0.2.0-beta.3"
      ...
    }
  }
  ...
}
```
