### ISSUE TITLE
Error: Failed to query available provider packages

### ISSUE THREAD

**Issue by gy0ung-git** [kbst/terraform-provider-kustomization#75]
I specified the provider as shown in the example and ran "terraform init" but failed with the following error: 
Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider
hashicorp/kustomization: provider registry registry.terraform.io does not have
a provider named registry.terraform.io/hashicorp/kustomization

Could you help me how to resolve this?

provider.tf 
terraform {
  required_providers {
    kustomization = {
      source = "kbst/kustomization"
      version = "0.3.0"
    }
  }
}

provider "kustomization" {
}

**Comment by gy0ung-git** [comment]
resolved after cleaning up .terraform.lock.hcl and previously used resources

**Comment by devinnasar** [comment]
I'm experiencing the same issue, however I've deleted .terraform.lock.hcl  and no previously used resources were created.
