### ISSUE TITLE
Some subdirectory issue

### ISSUE THREAD

**Issue by olfway** [kbst/terraform-provider-kustomization#81]
I'm trying to use kustomize with HelmChartInflationGenerator plugin and have some subdir-related issue

main.tf
```
data "kustomization_build" "argocd" {
  path = "argocd"
}
```

argocd/argocd.yaml
```
apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: argocd
chartName: argo-cd
chartRepoUrl: https://argoproj.github.io/argo-helm
chartVersion: 2.14.5
releaseName: argocd
values: argocd_values.yaml
```

argocd/argocd_values.yaml
```
fullnameOverride: "argocd"
```

argocd/kustomization.yaml
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo-cd
generators:
  - argocd.yaml
```

terraform plan
```
Error: kustomizationBuild: Kustomizer Run for path 'argocd' failed: Error: open argocd_values.yaml: no such file or directory
: failed to run command helm template argocd /private/var/folders/k7/yvvqm_q50252fx3g4gntx3v00000gq/T/kustomize-209626556/chart/argo-cd --values argocd_values.yaml

  on main_argocd.tf line 7, in data "kustomization_build" "argocd":
   7: data "kustomization_build" "argocd" {
```

Actually "kustomize  build argocd" has the same issue up to 3.9.2 version and starting 3.9.3 version it works fine.

I'm using kustomization version 0.3.1

**Comment by pst** [comment]
I currently can't upgrade to a later Kustomize api version than the one here: https://github.com/kbst/terraform-provider-kustomization/pull/79 due to the linked upstream regression. You can try building current master and see if that api version fixes your issue.

**Comment by pst** [comment]
Realizing it's about Argo-CD. I also maintain a native Kustomize base build from the upstream Argo-CD release: https://www.kubestack.com/catalog/argo-cd and I have a WIP branch that makes this (and other services from the catalog) available as native Terraform modules. https://github.com/kbst/catalog/pull/174

**Comment by olfway** [comment]
Tried kustomization 0.4.0 provider and it fixes this issue for me, thanks!

**Comment by pst** [comment]
Glad to hear that. Yeah, v0.4.0 released just in time then. Wasn't sure if I'd get through all testing by today when I suggested trying master this morning.
