### ISSUE TITLE
terraform crash while doing kustomization_overlay

### ISSUE THREAD

**Issue by u-anna** [kbst/terraform-provider-kustomization#92]
Hi, 

while trying to do a `kustomization_overlay`, the execution of `terraform plan` keeps crashing using kustomization provider version 0.4.1. or 0.4.2. 
Using version 0.4.0 it works just fine. 
I am using Terraform version 0.13.2.

My provider:
```terraform
provider "kustomize" {}
```

Output: 
```
Error: rpc error: code = Unavailable desc = transport is closing
```

[crash.log](https://github.com/kbst/terraform-provider-kustomization/files/6062805/crash.log)

**Comment by pst** [comment]
Seems like an issue with Windows paths not being handled correctly. I'll see what I can do.

**Comment by pst** [comment]
Please provide the Terraform and YAML to reproduce this.

**Comment by u-anna** [comment]
The Terraform and YAML are in the attatched .zip.

[kustomization-terraform.zip](https://github.com/kbst/terraform-provider-kustomization/files/6068795/kustomization-terraform.zip)

Please let me know if you need more information.

**Comment by pst** [comment]
I can confirm the issue on Windows. But I do not know what causes it. My access to a Windows machine for development is limited.

What you can do is, define the Kustomization as desired in YAML and use the `kustomization_build` data source to build it. But your Kustomization currently doesn't build using the Kustomize CLI. So I'd fix that first, then move on to use the provider again. Of course, this means you can't use Terraform variables in your Kustomization.

Unfortunately, unless somebody steps up and fixes this for Windows, this is the best I can do for now.

**Comment by pst** [comment]
Related upstream issue: https://github.com/kubernetes-sigs/kustomize/issues/963
