### ISSUE TITLE
apiVersion update

### ISSUE THREAD

**Issue by olfway** [kbst/terraform-provider-kustomization#93]
As I understand kustomization_build generate documents ids with apiversion included, ie:
```
networking.k8s.io_v1_IngressClass|~X|nginx
```

I tried to change apiVersion in manifest and it seems that terraform is going to recreate resource, for example:
```
  # kustomization_resource.ingress["networking.k8s.io_v1_IngressClass|~X|nginx"] will be destroyed
  - resource "kustomization_resource" "ingress" {
      - id       = "47b05ffa-0a9d-44af-886b-a8abe8346818" -> null
      - manifest = jsonencode(
            {
              - apiVersion = "networking.k8s.io/v1"
              - kind       = "IngressClass"
              - metadata   = {
                  - annotations = {
                      - ingressclass.kubernetes.io/is-default-class = "true"
                    }
                  - labels      = {
                      - app.kubernetes.io/managed-by = "terraform"
                    }
                  - name        = "nginx"
                }
              - spec       = {
                  - controller = "k8s.io/ingress-nginx"
                }
            }
        ) -> null
    }

  # kustomization_resource.ingress["networking.k8s.io_v1beta1_IngressClass|~X|nginx"] will be created
  + resource "kustomization_resource" "ingress" {
      + id       = (known after apply)
      + manifest = jsonencode(
            {
              + apiVersion = "networking.k8s.io/v1beta1"
              + kind       = "IngressClass"
              + metadata   = {
                  + annotations = {
                      + ingressclass.kubernetes.io/is-default-class = "true"
                    }
                  + labels      = {
                      + app.kubernetes.io/managed-by = "terraform"
                    }
                  + name        = "nginx"
                }
              + spec       = {
                  + controller = "k8s.io/ingress-nginx"
                }
            }
        )
    }
```

that's probably not very important for stateless resources, but it could be important for stateful and I think it's important for crd

Maybe there is should be an option for kustomization_build to not use apiVersion in generated resources ids?

**Comment by pst** [comment]
You're probably right, this was a naive oversight from me. I have done some experiments am thinking about how to best move forward.

Changing these IDs will be a breaking change for all existing users. But it probably makes most sense to change it for new users and leave a `legacy_ids = true` kind of argument or something like that.

Open for feedback.

**Comment by pst** [comment]
https://github.com/kbst/terraform-provider-kustomization/pull/104

**Comment by pst** [comment]
Potentially a StateUpgrader function could be used to handle the changing IDs.

https://github.com/hashicorp/terraform-plugin-sdk/blob/b5604678a4d0326c5c94366bb89bb7d3ad06bc29/helper/schema/resource.go#L96

**Comment by willthames** [comment]
Looks like StateUpgrader is only useful for manipulating the contents of the state, not the resource ID of the state.

I think a major version bump to signal a breaking API, with a documented helper script, might be the way around this.

And then there's the question of whether to capture group information in resource IDs or not - as Kinds can potentially be ambiguous (which is the whole point of the group), there'd still need to be a workaround for e.g. extensions -> apps changes.

**Comment by pst** [comment]
The [v0.6.0 release](https://github.com/kbst/terraform-provider-kustomization/releases/tag/v0.6.0) includes a new ID format by @willthames (opt-in for this release). It can be enabled with `legacy_id_format = false` to test it. We're planning to make the new format the default in the next release and keep the legacy option for backwards compatibility with existing configurations.

**Comment by pst** [comment]
With [v0.7.0](https://github.com/kbst/terraform-provider-kustomization/releases/tag/v0.7.0) out, this is done.
