### ISSUE TITLE
using tf templates feature with kustomize

### ISSUE THREAD

**Issue by MrHassanMurtaza** [kbst/terraform-provider-kustomization#98]
Hi,

we have the following setup: 
- k8s-bases -- which contains all the bases - pure Kubernetes manifests. 
- k8s-addons (overlays)-- to apply add-ons using kustomize provider in terraform. 

we are looking for a way to treat our k8s-addons as templates so that we can pass the dynamic variables from terraform (example use-case: if you're using kube2iam then you need to pass roles created by another module). 

I tried using tf templates and passing rendered templates but it doesn't seem to work in this way.

The only workaround is to run the terraform initially to generate the manifests from templates and then pointing the kustomize provider to generate manifests. this manual step essentially breaks the automation pipeline since we are applying before planning the tf.

**Comment by pst** [comment]
Have you tried the `kustomization_overlay`? https://registry.terraform.io/providers/kbst/kustomization/latest/docs/data-sources/overlay
